### PR TITLE
Friendly fork merge

### PR DESCRIPTION
**Pull request by b1n-ch1kn**
Hello there,
I'm intrigued with what you've been working on in this fork. It looks like quality stuff and I'm impressed how well your additions integrate with our software stack.
What's been your motivation to build on our progress?

Happy to chat about this stuff,
Alastair

### CODE REVIEW

**Comment by liamferrante** [comment]
> Hello there, I'm intrigued with what you've been working on in this fork. It looks like quality stuff and I'm impressed how well your additions integrate with our software stack. What's been your motivation to build on our progress?
> 
> Happy to chat about this stuff, Alastair

I second this

**Comment by TheEppicJR** [comment]
I don't think I merged that correctly but oh well.
You guys were kind enough to provide this framework/setup for a ROS2 workspace that connects to the Formula Student Driverless Simulation with some actual documentation on how to get started, which is the only reason I've been able to get this far. I'm trying test the waters and build some interest within my own team to possibly try this in the next year or two.
I've been trying to keep everything I do completely interoperable with what you have because hard forking is dumb. 
The next thing I'm going to start working on is fusing the lidar and vision cone detections into cones in the global reference frame, hopefully taking the odometry and covariance from whatever you guys end up making for the EKF SLAM node.
Thanks Alastairs and Liam

**Comment by b1n-ch1kn** [comment]
Thats pretty neat, where is your team from? It's cool our repo has helped others get started, must mean we've been doing something right haha.
Also, have you added a 3rd camera for depth to the FSDS `settings.json`? I noticed you had a node replicating the Zed camera, which was really cool.

Feel free to add me on LinkedIn if you have: https://www.linkedin.com/in/alastair-bradford/. Or discord: B1n Ch1kn#8364.

Hope your progress continues along nicely 
-Alastair

**Comment by TheEppicJR** [comment]
The depth camera really and that repeater node that pretends to be the Zed camera are a little too much for my computer, I intend to make that node a bit faster. I haven't been able to get the TRT node to work so idk if that depth camera works correctly with it, and I assume adding the 0.3m to 20m limits to the depth camera might be useful (I also tried to make a debug image that is scaled so that those limits are the range so you can actually see something out of the 32FC1 image)
And I am from the San Jose State team from California

**Pull request merged**
